working_dir: "tmp/working_dir"
pool:
  catalog:
    - item_id: "diamond"
      quantity: 100
      probability: 10
    - item_id: "gold"
      quantity: 1000
      probability: 20
    - item_id: "silver"
      quantity: 10000
      probability: 30
    - item_id: "rock"
      quantity: 100000
      probability: 40
    - item_id: "mud"
      quantity: -1
      probability: 70
    - item_id: "log"
      quantity: -1
      probability: 50
wal:
  max_file_size_kb: 512
  max_request_buffer_size: 512
  formatter: "string_line"
  flush_after_n_draw: 200
grpc:
  enabled: true
  listen_address: ":50051"
