working_dir: "tmp/working_dir"
pool:
  catalog:
    - item_id: "diamond"
      quantity: 100
      probability: 10
    - item_id: "gold"
      quantity: 100
      probability: 20
    - item_id: "silver"
      quantity: 100
      probability: 30
    - item_id: "rock"
      quantity: 100
      probability: 40
wal:
  max_file_size_kb: 1024
  max_request_buffer_size: 512
  formatter: "json"
  flush_after_n_draw: 20
